{{- if .Values.poolsExtractor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pools-{{ include "blockscout-admin.fullname" . }}-config
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
data:
  networks.json: |
    {
      "networks": {
        {{- $len := len .Values.config.network }}
        {{- range $i, $value := .Values.config.network }}
        "{{ .id }}": {
          "coingecko_terminal_network_id": "{{ .coingecko_terminal_network_id }}"
        }{{- if ne (sub $len 1) $i }},{{- end }}
       {{- end }}
      }
    }
{{- end }}
