{{- if .Values.config.fetchL2Metadata.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "da-indexer.fullname" . }}-config
  labels:
    {{- include "da-indexer.labels" . | nindent 4 }}
data:
  celestia_routes.toml:
    {{ toYaml .Values.config.fetchL2Metadata.routes | indent 4 }}
{{- end }}