apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "da-indexer.fullname" . }}-config
  labels:
    {{- include "da-indexer.labels" . | nindent 4 }}
data:
  celestia_routes.toml:
    {{ toYaml .Values.config.routes | indent 4 }}
