{{- if .Values.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "da-indexer.fullname" . }}-env
  labels:
    {{- include "da-indexer.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
---
{{- if .Values.config.indexer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "da-indexer.fullname" . }}-db-config
  labels:
    {{- include "da-indexer.labels" . | nindent 4 }}
type: Opaque
data:
  databaseUrl: {{ .Values.config.indexer.databaseUrl | b64enc }}
{{- end }}