{{- if .Values.frontend.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-revokescout.fullname" . }}-frontend-env
  labels:
    {{- include "blockscout-revokescout.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.frontend.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
