apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout-ens.fullname" . }}-bens
  labels:
    app: {{ .Release.Name }}-bens
    {{- include "blockscout-ens.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bens.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ens
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/blockscout-ens-secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-blockscout
        {{- include "blockscout-ens.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blockscout-ens.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.bens.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}-bens
          securityContext:
            {{- toYaml .Values.bens.securityContext | nindent 12 }}
          image: "{{ .Values.bens.image.repository }}:{{ .Values.bens.image.tag }}"
          resources:
            {{- toYaml .Values.bens.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.bens.image.pullPolicy }}
          {{- with .Values.bens.command }}
          command:  {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.bens.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8050
              protocol: TCP
          ports:
            - name: metrics
              containerPort: 6060
              protocol: TCP
          env:
          {{- range $key, $value := .Values.bens.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "blockscout-ens.fullname" . }}-bens-env
          {{- if .Values.bens.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.bens.readinessProbe.path }}
              port: http
              scheme: HTTP
            {{- with .Values.bens.readinessProbe.params }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.bens.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.bens.livenessProbe.path }}
              port: http
              scheme: HTTP
            {{- with .Values.bens.livenessProbe.params }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bens.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
