apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-contract-verification.fullname" . }}-sig-provider
  labels:
    {{- include "smart-contract-verification.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sigProvider.service.type }}
  ports:
    - port: {{ .Values.sigProvider.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app: {{ include "smart-contract-verification.fullname" . }}-sig-provider
    {{- include "smart-contract-verification.selectorLabels" . | nindent 4 }}
