apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-proxy-verifier.fullname" . }}-svc
  labels:
    app: {{ .Release.Name }}-svc
    {{- include "blockscout-proxy-verifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxyVerifier.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 6060
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Release.Name }}
