apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-points.fullname" . }}-backend
  labels:
    app: {{ include "blockscout-points.fullname" . }}-backend
    {{- include "blockscout-points.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.backend.config.grpc.enabled }}
    - port: {{ .Values.backend.config.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end}}
    {{- if .Values.backend.metrics.enabled }}
    - port: {{ .Values.backend.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app: {{ include "blockscout-points.fullname" . }}-backend
