{{- if .Values.bot.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-points.fullname" . }}-bot-env
  labels:
    {{- include "blockscout-points.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.bot.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
