apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-points.fullname" . }}
  labels:
    {{- include "blockscout-points.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.grpc.enabled }}
    - port: {{ .Values.config.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end}}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "blockscout-points.selectorLabels" . | nindent 4 }}
