{{- if and .Values.metrics.enabled .Values.metrics.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blockscout-points.fullname" . }}
  labels:
    {{- include "blockscout-points.labels" . | nindent 4 }}
spec:
  endpoints:
  - scrapeTimeout: 30s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blockscout-points.fullname" . }}
{{- end }}