apiVersion: v1
kind: Service
metadata:
  name: {{ include "autoscout.fullname" . }}
  labels:
    app: {{ include "autoscout.fullname" . }}
    {{- include "autoscout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "autoscout.fullname" . }}
    {{- include "autoscout.selectorLabels" . | nindent 4 }}
