apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quicknode-marketplace-integration.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quicknode-marketplace-integration.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.config.databaseUrl | b64enc | quote }}
  BASIC_AUTH_USERNAME: {{ .Values.config.basicAuth.username | b64enc | quote }}
  BASIC_AUTH_PASSWORD: {{ .Values.config.basicAuth.password | b64enc | quote }}
  QN_SSO_SECRET: {{ .Values.config.qnSsoSecret | b64enc | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc | quote }}