{{- if and .Values.blockscout.enabled .Values.config.prometheus.blackbox.enabled }}
{{- $url := printf "https://%s/api/health" .Values.blockscout.ingress.hostname }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-blockscout-bb
  labels:
    {{- include "blockscout-stack.labels" . | nindent 4 }}
spec:
  endpoints:
  - scrapeTimeout: 5s
    port: http
    path: "/probe"
    interval: 15s
    params:
      module:
      - http_2xx
      target:
      - {{ $url }}
    metricRelabelings:
      - targetLabel: instance
        replacement: {{ $url }}
      - targetLabel: target
        replacement: {{ include "blockscout-stack.fullname" . }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter
{{- end }}
