apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zilliqa-validators-indexer.fullname" . }}-env
  labels:
    {{- include "zilliqa-validators-indexer.labels" . | nindent 4 }}
type: Opaque
data:
  ETH_RPC_URL: {{ .Values.config.ethRpcUrl | b64enc }}
  DB_URL: {{ .Values.config.dbUrl | b64enc }}
